### ISSUE TITLE
Fix flaky test

### ISSUE THREAD

**Issue by sdemagny** [numerique-gouv/people#326] opened 2024-08-07 13:24 UTC
`test_api_team_accesses_list_authenticated_ordering_user[name]` sometimes fails and then passes

`test_api_mail_domains__list_authenticated` sometimes fails, sometimes fails not

**Comment by sdemagny** [comment] 2024-08-07 13:30
voir aussi `test_api_mail_domains__list_authenticated`

**Comment by Morendil** [comment] 2024-08-07 13:35
Also on my end `test_api_team_accesses__list_find_members_by_email`

My initial thought was to blame this on test being run in parallel. However it's not clear to me how this particular test could fail as a result of a race condition.

Here is the JSON of the reported response (which fails because it returns two users matching BRUNE, when there should be only one)

`{'count': 2, 'next': None, 'previous': None, 'results': [{'id': '8d5831dd-583a-40c4-8d92-73e961d3fb47', 'user': {'id': 'a34381b9-e88e-4c4b-a9c5-683a4d2f792c', 'email': 'brooksdawn@example.net', 'name': None}, 'role': 'administrator', 'abilities': {'delete': True, 'get': True, 'patch': True, 'put': True, 'set_role_to': ['member']}}, {'id': 'cf605a07-43f1-472f-8d88-828f6c56991f', 'user': {'id': 'eef5968b-e725-408c-abcc-62bc4c8eb129', 'email': 'reinebrunehaut@gouv.fr', 'name': None}, 'role': 'administrator', 'abilities': {'delete': True, 'get': True, 'patch': True, 'put': True, 'set_role_to': ['member']}}]}`

The user `brooksdawn@example.net` does not match BRUNE so I don't see why it should be returned by the search, race condition or not.

**Comment by Morendil** [comment] 2024-08-12 09:36
On further investigation, I'm reproducing the intermittent failures in `test_api_team_accesses__list_find_members_by_email ` and in `test_api_mail_domains__list_authenticated ` even when running the test in isolation and with no parallelism. It sometimes takes many repetitions (up to 80 so far) but failures still. This is starting to look less like a problem with the test and more like a potential bug…

I'm trying to get a grip on debugging from VSCode when the tests are running inside a container.

**Comment by Morendil** [comment] 2024-08-21 12:19
After further investigation: the intermittent failure is due to a conjunction of three factors
- the offending test leaves the email of the user searching for team-mates undefined
- because of this, the email is filled in randomly by FactoryBoy
- on the API side the query relies on trigram matching, rather than exact matching

So, for the test to fail, what has to happen is that FactoryBoy generates an email address that is "close enough" to the query string (BRUNE); then, the search happens to pick up two matching emails from the same team as the user on whose behalf the query is run: the expected other user (with email `reinebrunehaut@gouv.fr`) and (unexpectedly) the requesting user themselves, as in the above run, with email `brooksdawn@example.net`. I'm not very familiar with trigram searches but my rough understanding is that "brooksdawn" matches "BRUNE" closely enough, based on the two letters "br".

My suggestion is a layered response, in the spirit of [QRQC](https://healthtech.theodo.com/blog/how-qrqc-helps-me-better-manage-bugs-on-my-project):

- a quick fix is to assign a fixed, non-matching email to the requesting user; I will propose a PR shortly
- a longer term and complete resolution would entail resolving what seems to me a clash of mental models: the way the test is written suggests that the expectation, in terms of search semantics, was for an exact substring match; and trigram searching is an unusual choice which does not match that mental model

> I'm trying to get a grip on debugging from VSCode when the tests are running inside a container.

✅  This is non-trivial, but solved. It requires adding pydebug to the dependencies of the app portion, opening port 5678 in Docker, and creating an "attach" type launch.json configuration targeting that same port; while at the same time setting up the devcontainer to target the app-dev service for test discovery.

**Closed** 2024-10-28 19:34 UTC
