### ISSUE TITLE
Duplicated team's name error message

### ISSUE THREAD

**Issue by lebaudantoine** [numerique-gouv/people#74] opened 2024-02-23 14:05 UTC
## Feature Request
<img width="453" alt="306046800-83926992-026c-42c9-8ce9-3976820ccc82" src="https://github.com/numerique-gouv/people/assets/45729124/33cb9e1f-4bc9-4129-8bdf-9039b8162d67">

When creating a team with a duplicated team's name, the error message is not explicit for the user.

**Describe the solution you'd like**
The error message should mention name-related error, ex: "A team with this name already exists."

**Comment by Morendil** [comment] 2024-11-05 21:03
Duplicate of #293… to be fair it's the newer issue that's a duplicate ! But it's the one that's in the kanban board, so closing this one.

**Closed by Morendil** 2024-11-05 21:03 UTC
Labels: enhancement
